name: Java CI with Maven - Test and package

on:
  pull_request:
    branches:
      - 'main'

jobs:
  Package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Maven Code Quality
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ secrets.SONAR_TOKEN }} | sed 's-/-_-')
